package com;// Generated by Selenium IDE

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class WesternUnionTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:/chromedriver.exe");
  }

  @After
  public void tearDown() {
  }

  @Test
  public void westernUnion()
      throws InterruptedException, IOException {
    try {
      for (int i = 0; i < 1440; i++) {

        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        driver
            .get("https://www.westernunion.com/us/en/web/send-money/start?SrcCode=12345&ReceiveCountry=IN&SendAmount=100&ISOCurrency=CNY&FundsOut=BA&FundsIn=CreditCard");
//      driver.manage().window().setSize(new Dimension(1050, 704));

        Thread.sleep(2000);

        driver.findElement(By.id("button-fraud-warning-accept")).click();

        Thread.sleep(10000);

        String exchangeRate = driver
            .findElement(By.id("smoExchangeRate")).getText();
//      By.id("smoExchangeRate");
        vars.put("exchangeRate", exchangeRate);

        Date date = Calendar.getInstance().getTime();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
        String strDate = dateFormat.format(date);

        String json =
            "{ \"date\" : \"" + strDate + "\", \"exchangeRate\" : \""
                + exchangeRate
                + "\"}, \n";

        OutputStream os =
            new FileOutputStream(new File("C:/exchangeRate.txt"), true);

        os.write(json.getBytes(), 0, json.length());
        os.close();

        driver.close();
        driver.quit();

        Thread.sleep(900000);

      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
}
